language: node_js
node_js:
  - "6.9"

branches:
  only:
    - dev

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng build --prod --aot --no-progress

after_success:
  - ./deploy.sh

cache:
  directories:
    - node_modules
