image: Visual Studio 2017

environment:
  nodejs_version: "5.7.1"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn global add npm@$env:nodejs_version --no-progress

test_script:
  - yarn ng build --prod --aot --no-progress
  - yarn lint

build: off

cache:
  - node_modules -> yarn.lock
  - "%LOCALAPPDATA%/Yarn"

branches:
  only:
  - master
